### ISSUE TITLE
在配置的时候遇到跨域报错

### ISSUE THREAD

**Issue by XLearner** [a1029563229/blogs#20]
![image](https://user-images.githubusercontent.com/26158725/112840662-344e2300-90d2-11eb-948b-9a15d1121094.png)
如上图所示，注册微应用之后，依旧有报跨域的错误。webpack的配置也配置了，如下图所示：
![image](https://user-images.githubusercontent.com/26158725/112841350-f56c9d00-90d2-11eb-9681-29851bff61af.png)
检查了之后发现设置的  "Access-Control-Allow-Origin": "*"  没有生效：
![image](https://user-images.githubusercontent.com/26158725/112841558-35338480-90d3-11eb-82c3-1ba971f3dab9.png)
请大神赐教😖

**Comment by a1029563229** [comment]
从响应结果来看，跨域配置未成功
可以用 postman 调试查看跨域头是否设置成功
