### ISSUE TITLE
windows环境packages/vite中build老报错？改不动了，不知作者有遇到否

### ISSUE THREAD

**Issue by ajunc** [a1029563229/blogs#82]
1、'eslint' is not recognized as an internal or external command
2、缺少.eslintrc.cjs文件
3、lint检查报错：
`
F:\vite\vite-source-code\packages\vite\src\client\client.ts
  1:1  error  Parsing error: The keyword 'import' is reserved

F:\vite\vite-source-code\packages\vite\src\client\env.ts
  1:9  error  Parsing error: Unexpected token const

F:\vite\vite-source-code\packages\vite\src\client\overlay.ts
  1:1  error  Parsing error: The keyword 'import' is reserved

F:\vite\vite-source-code\packages\vite\src\client\tsconfig.json
  2:12  error  Parsing error: Unexpected token :

F:\vite\vite-source-code\packages\vite\src\node\__tests__\asset.spec.ts
  1:1  error  Parsing error: The keyword 'import' is reserved
`
4、'run-s' is not recognized as an internal or external command

........

**Comment by ajunc** [comment]
我是下载的vite源码来调试

**Comment by a1029563229** [comment]
可以全局安装 eslint 依赖尝试解决
